version: 0.2
phases:
  install:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - git show
artifacts:
  files:
    - "**/*"
