version: 0.2
phases:
  install:
    commands:
      - echo This is new
  pre_build:
    commands:
      - printenv
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_TRIGGER
artifacts:
  files:
    - "**/*"
